### ISSUE TITLE
No such variable: bismark_dedup_log_1 error when using --rrbs

### ISSUE THREAD

**Issue by drejom** [SciLifeLab/NGI-MethylSeq#24]
I'm getting an error when running the pipeline with the `--rrbs` switch; run starts trimming etc without `--rrbs`...
  
```
$ nextflow run $NF/bismark.nf -profile base --reads '*_R{1,2}_001.fastq' --genome mm10 --rrbs

N E X T F L O W  ~  version 0.25.4
Launching `NGI-MethylSeq/bismark.nf` [crazy_monod] - revision: 566634b95a
==================================================
 NGI-MethylSeq : Bisulfite-Seq Best Practice v0.2
==================================================
...
[warm up] executor > local
ERROR ~ No such variable: bismark_dedup_log_1

 -- Check script 'bismark.nf' at line: 413 or see '.nextflow.log' file for more details
```

**Comment by Shellfishgene** [comment]
I have the same error...

**Comment by ewels** [comment]
Aha, thanks for reporting this! I must confess, I don't think I've actually tried to run in RRBS mode yet, I just added those options for future proofing.. :) I'll add it to the travis tests and look into the bug!

**Comment by ewels** [comment]
Ok, I think that should have fixed things - let me know if you run into any more problems, and thanks for reporting!

Phil

**Comment by ewels** [comment]
(the new and improved testing showed up a few other minor issues, now also hopefully fixed!)
