### ISSUE TITLE
Bismark error with single end RRBS reads

### ISSUE THREAD

**Issue by Shellfishgene** [SciLifeLab/NGI-MethylSeq#25]
Using single end RRBS reads produces the following Bismark error:
`You can only specify --ignore_r2 for paired-end result files`
Should be easy to fix...

**Comment by ewels** [comment]
Already fixed ;) Apologies, been slowly iterating through different RRBS bugs this morning with the new travis test. Will put together a PR and merge into this repo now that the tests are [passing](https://travis-ci.org/ewels/NGI-MethylSeq).

**Comment by ewels** [comment]
Ok, PR merged - please have a go with this new version and let me know if you still hit any problems..

Phil
