### ISSUE TITLE
igenomes.config 

### ISSUE THREAD

**Issue by drejom** [SciLifeLab/NGI-MethylSeq#31]
Hi @ewels,
First off, thanks once again for making these pipelines available. I'm trying to get our sequencing core to adopt these or something similar. I'm happy to contribute where I can - is it better to create an issue like this, or are you happy for others to contribute pull requests? I'm new to git, but getting the hang of it. 

I'm following the RNAseq pipline and got a bit lost in the discussions about curly brackets for igenomes.config: SciLifeLab/NGI-RNAseq#152. I found this pipeline didn't work (java/groovy errors) with curly brackets around paths, but it does without - see attached [igenomes.config](https://github.com/SciLifeLab/NGI-MethylSeq/files/1392646/igenomes.config.txt)

**Comment by ewels** [comment]
Hi @drejom,

Glad you're finding them helpful! Issues are the perfect place for discussion, and forking + contribution via pull requests are very welcome.

The curly bracket stuff did get confusing sorry - I think that it's now resolved and working for the RNAseq pipeline but I haven't yet applied this fix to this MethylSeq pipeline, you're right. I'll do this update now.

Phil

**Comment by ewels** [comment]
Hi @drejom,

I think I've fixed this now in the above commit. If you could have a play and let me know how you get on, that would be great!

Thanks,

Phil
