### ISSUE TITLE
compareTo logic fix

### ISSUE THREAD

**Issue by drejom** [SciLifeLab/NGI-MethylSeq#32]
Similar to SciLifeLab/NGI-RNAseq#152

`nextflow.config` needs updating

```
// Function to ensure that resource requirements don't go beyond
// a maximum limit
def check_max(obj, type) {
  if(type == 'memory'){
    if(obj.compareTo(params.max_memory) == 1)
      return params.max_memory
    else
      return obj
  } else if(type == 'time'){
    if(obj.compareTo(params.max_time) == 1)
      return params.max_time
    else
      return obj
  } else if(type == 'cpus'){
    return Math.min( obj, params.max_cpus )
  }
}
```
Another fix is to invert the order of return statements, but I guess testing ==1 is more explicit?

**Comment by ewels** [comment]
Yes, I have a feeling that I tried inverting the order first and it didn't work for some reason..? Thanks though, good spot. I need to get better at passing these bugfixes across all pipelines!
